# Gitleaks configuration file
# See https://github.com/gitleaks/gitleaks/#configuration for full configuration options

# Title for the gitleaks configuration
title = "Arkad App Flutter Gitleaks Configuration"

# By default, gitleaks will check all commits in a repository
# Set to true if you want to only scan the current HEAD diff
[extend]
useDefault = true # Use default rulesets along with your custom rules below

# Define paths to exclude from scanning
[allowlist]
paths = [
  '''pubspec.lock''',
  '''build/''', 
  '''\.gradle/''',
  '''gradle/''',
  '''\.dart_tool/''',
  '''.idea/''',
  '''android/gradle/wrapper/gradle-wrapper.jar''',
  # Add other paths you want to exclude here
]

# You can also define specific regexes to whitelist
# For example, if you have non-secret sample keys in documentation
# regexes = [
#   '''sampleApiKey123''',
#   '''example-token-used-in-docs'''
# ]