hooks:
  post_create:
    # Copy real files from the MAIN worktree into the NEW worktree
    - type: copy
      from: "ios/Runner/GoogleService-Info.plist" # Allowed even if gitignored. 'from' is always relative to the MAIN worktree
      to: "ios/Runner/GoogleService-Info.plist" # Destination is relative to the NEW worktree
    - type: copy
      from: "lib/firebase_options.dart" # Allowed even if gitignored. 'from' is always relative to the MAIN worktree
      to: "lib/firebase_options.dart" # Destination is relative to the NEW worktree
    - type: copy
      from: "android/app/google-services.json " # Allowed even if gitignored. 'from' is always relative to the MAIN worktree
      to: "android/app/google-services.json " # Destination is relative to the NEW worktree
    - type: copy
      from: "api" # Allowed even if gitignored. 'from' is always relative to the MAIN worktree
      to: "api" # Destination is relative to the NEW worktree
    - type: copy
      from: "assets" # Allowed even if gitignored. 'from' is always relative to the MAIN worktree
      to: "assets" # Destination is relative to the NEW worktree

    - type: copy
      from: "env" # Allowed even if gitignored. 'from' is always relative to the MAIN worktree
      to: "env" # Destination is relative to the NEW worktree
