repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        types: [dart]
        pass_filenames: false

      - id: dart-format
        name: Dart Format
        entry: dart format .
        language: system
        types: [dart]
        pass_filenames: false

      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        types: [dart]
        pass_filenames: false
        stages: [push]

      - id: flutter-build
        name: Flutter Build
        entry: flutter build apk --debug
        language: system
        types: [dart]
        pass_filenames: false
        stages: [push] 