name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  file_picker: ^8.0.7
  image_picker: ^1.0.4
  url_launcher: ^6.1.14
  english_words: ^4.0.0
  provider: ^6.1.2
  path_provider: ^2.1.1
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
