name: CI - Analyze and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.0"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

  build:
  name: Build application
  needs: analyze
  strategy:
    matrix:
      include:
        - platform: android
          os: ubuntu-latest
        - platform: ios
          os: macos-latest

  runs-on: ${{ matrix.os }}

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.29.0"
        channel: "stable"
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build for ${{ matrix.platform }}
      run: |
        PLATFORM=${{ matrix.platform }}
        if [ "$PLATFORM" = "android" ]; then
          flutter build apk --release
        elif [ "$PLATFORM" = "ios" ]; then
          flutter build ios --no-codesign
        fi
