name: CI - Analyze and Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLUTTER_VERSION: "3.29.0"
  OPENAPI_GENERATOR_VERSION: "7.10.0"

jobs:
  generate-api:
    name: Generate API Client
    runs-on: ubuntu-latest
    outputs:
      api-hash: ${{ steps.api-hash.outputs.hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get API Spec Hash
        id: api-hash
        run: |
          API_HASH=$(curl -sf --max-time 30 --retry 2 --retry-delay 5 \
            "https://staging.backend.arkadtlth.se/api/openapi.json" | sha256sum | cut -d' ' -f1)
          echo "hash=$API_HASH" >> $GITHUB_OUTPUT
          echo "API spec hash: $API_HASH"

      - name: Cache Generated API Client
        id: api-cache
        uses: actions/cache@v4
        with:
          path: api/arkad_api/
          key: api-client-${{ steps.api-hash.outputs.hash }}

      - name: Install pnpm
        if: steps.api-cache.outputs.cache-hit != 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        if: steps.api-cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Set up Flutter
        if: steps.api-cache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Install OpenAPI Generator
        if: steps.api-cache.outputs.cache-hit != 'true'
        run: pnpm install -g @openapitools/openapi-generator-cli

      - name: Generate API Client
        if: steps.api-cache.outputs.cache-hit != 'true'
        run: |
          # Clean and generate
          rm -rf api/arkad_api
          mkdir -p api

          openapi-generator-cli generate \
            -i "https://staging.backend.arkadtlth.se/api/openapi.json" \
            -g dart-dio \
            -o api/arkad_api \
            --additional-properties=pubName=arkad_api,pubVersion=1.0.0,pubDescription="Generated API client",nullSafe=true

          # Complete generation
          cd api/arkad_api
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          cd ../..

  analyze-and-format:
    name: Analyze & Format
    needs: generate-api
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Restore API Client Cache
        uses: actions/cache@v4
        with:
          path: api/arkad_api/
          key: api-client-${{ needs.generate-api.outputs.api-hash }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --no-fatal-infos

      - name: Check code formatting
        run: |
          if ! dart format --set-exit-if-changed lib/; then
            echo "Code formatting issues found. Run 'dart format lib/' to fix."
            exit 1
          fi